### PR TITLE
Try to fix sphinx problem by restricting tensorflow-model-optimization

### PR DESCRIPTION
**Pull request by jmitrevs**
# Description

The sphinx build failed. This tries to restrict incompatible versions

- [x] Bug fix (non-breaking change that fixes an issue)

## Tests

Check the sphinx build

## Checklist

- [x] I have read the [guidelines for contributing](https://github.com/fastmachinelearning/hls4ml/blob/main/CONTRIBUTING.md).
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have installed and run `pre-commit` on the files I edited or added.
- [x] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by jmitrevs** [comment]
@jmduarte, @vloncar, is this the type of fix you think is appropriate for sphinx? This is actually for everyone that install hls4ml.

**Comment by vloncar** [comment]
After some more digging, this is due to the split from keras and TF and the way this is handled in TF 2.15 onwards. Apparently, TFMOT works only with keras 2.x from TF (`tf.keras`) and after the split this is provided by the [tf_keras](https://pypi.org/project/tf-keras/) package. TFMOT added this to `requrements.txt` but not to `setup.py` so it doesn't get installed on fresh environments. I opened tensorflow/model-optimization#1117 to track this. I propose we wait for the resolution of that one in a timely manner, and if not, we go with this workaround.

**Comment by jmitrevs** [comment]
Do we need tf_keras in all cases? Maybe we should add it to our requirements.

If we add tf_keras then we don't need to restrict tensorflow-model-optimization, right?

**Comment by jmitrevs** [comment]
I am going to try the alternate solution to see if it works.

**Comment by vloncar** [comment]
tf_keras only exists for 2.14.1 and 2.15. Not sure if this will force the tensorflow to that version or if not, will it affect precious tensorflow versions. I also didn't figure out what would happen if I install keras 3. This situation is a bit of a mess :slightly_smiling_face:

**Comment by jmitrevs** [comment]
The alternate version may be more problematic based on your comments, so I won't push it. (I do think it works in my setup, though.) So we wait to see if it gets solved upstream first?

**Comment by jmitrevs** [comment]
Ideally this is a *temporary* fix that will be reverted.

**Pull request merged**
