### PR TITLE
Add View to layer name map for pytorch parser

### PR DESCRIPTION
**Pull request by JanFSchulte**
Add a mapping of 'view' -> "View" to the pytorch converter to allow this type of operation to be parsed correctly. Fixes https://github.com/fastmachinelearning/hls4ml/issues/1038

## Type of change

For a new feature or function, please create an issue first to discuss it
with us before submitting a pull request.

Note: Please delete options that are not relevant.

- [x] Bug fix (non-breaking change that fixes an issue)

## Tests

Verified that it fixes the crash reported in https://github.com/fastmachinelearning/hls4ml/issues/1038

**Test Configuration**:

## Checklist

- [x] I have read the [guidelines for contributing](https://github.com/fastmachinelearning/hls4ml/blob/main/CONTRIBUTING.md).
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have installed and run `pre-commit` on the files I edited or added.
- [x] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by vloncar** [comment]
Can we add a test? Basically a simpler version of what was done in the bug report

**Comment by JanFSchulte** [comment]
Yep, working on it.

**Comment by JanFSchulte** [comment]
Should we add Vitis also for the other tests in this file while we're at it?

**Comment by vloncar** [comment]
Ah, I didn't notice we don't do Vitis in these tests. I guess we can add it now, but maybe as a separate PR.

**Comment by JanFSchulte** [comment]
Not quite sure anymore why I didn't include it in the first place. I can prepare a separate PR to add it everywhere.

**Review by vloncar — APPROVED** [review]

**Pull request merged**
