### PR TITLE
change master to main

### PR DESCRIPTION
**Pull request by jmitrevs**
# Description

This PR is just for any changes that we need to make while renaming master to main.

## Type of change

For a new feature or function, please create an issue first to discuss it
with us before submitting a pull request.

Note: Please delete options that are not relevant.

- [x] Other (Specify)

## Tests

**Test Configuration**:

## Checklist

- [x] I have read the [guidelines for contributing](https://github.com/fastmachinelearning/hls4ml/blob/main/CONTRIBUTING.md).
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by thesps** [comment]
I think recent Jenkins test failures relate to this also, for example this fetch references `master` (from #600 [here](https://correlator2.fnal.gov:8080/blue/organizations/jenkins/hls4ml/detail/PR-600/4/pipeline)):
```
> git fetch --no-tags --force --progress -- https://github.com/fastmachinelearning/hls4ml.git +refs/pull/600/head:refs/remotes/origin/PR-600 +refs/heads/master:refs/remotes/origin/master # timeout=10
```
I don't think this is specified in any of our test code, so probably the Jenkins setup itself

**Comment by jmitrevs** [comment]
For the sphinx workflow, I have to admit I am not too familiar, but would it make sense that on main it build main, but on a release branch or tag it build the documentation for that tag? That should probably be the official version we upload.

**Comment by jmitrevs** [comment]
What do people think about this? The changes are minor, so I would propose merging it. About the proposed sphinx workflow change, I think that can be separate.

**Review by jmduarte — APPROVED** [review]
I think the changes look good to me. Also, for now we can keep the sphinx workflow running on main in case we "backport" documentation updates that describe prior releases.

**Pull request merged**
