### PR TITLE
RNN support (part 1)

### PR DESCRIPTION
**Pull request by vloncar**
As discussed before, this is the first stage of the RNN support. The PR includes the support for parsing RNN layers into the IR, as well as the Vivado-specific initialization. The same initialization specific to Quartus backend can be part of the second PR. After this is merged, parts 2 and 3 will add HLS implementations for Vivado and Quartus.

### CODE REVIEW

**Comment by vloncar** [comment]
Now also including Embedding layer from #449. @drankincms @jmduarte Can you take a look so we can merge this soon? I'd like to finish the port of Vivado RNN branch (aka part 2).

**Comment by drankincms** [comment]
So right now this crashes on a GRU I tried with because `get_valid_reuse_factors()` returns an empty list for the recurrent layers.
In the keras RNN branch I have something like this: https://github.com/drankincms/hls4ml/blob/keras-RNN-staticswitch/hls4ml/templates/vivado_template.py#L478-L501
There might be a better way to pass around `recr` for this purpose, but I want to make sure @vloncar you see this issue as something that this part 1  PR should solve first before I add a fix.

**Review by jmduarte — COMMENTED** [review]
@vloncar looks good from my side! I checked and the embedding layer works and synthesizes as expected in my models. We may want to address @drankincms's issue though.

**Comment by vloncar** [comment]
I added the RF fix from the ongoing port of the RNN branch. There will be more changes in PR2, namely the transposing of weights is moved to the optimizer, in line with the other layers, which in this PR is done in the initializer of Vivado RNN layers.

**Review by drankincms — APPROVED** [review]
All clear for me

**Pull request merged**
